/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TimeGet */

#ifndef _Included_TimeGet
#define _Included_TimeGet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TimeGet
 * Method:    timeaccess
 * Signature: (LTimeStorage;)V
 */
JNIEXPORT void JNICALL Java_TimeGet_timeaccess
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
